name: Run Python Cron Job

on:
  schedule:
    # This schedule runs at 3 AM, 7 AM, 11 AM, 3 PM, and 7 PM UTC from mon-fri
    - cron: '0 3,7,11 * * 1-5' 
  workflow_dispatch: # Allows for manual triggering

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Debug Path
      run: |
        pwd
        ls -la

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_PROJECT_KEY_ID: ${{ secrets.GOOGLE_PROJECT_KEY_ID }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
      run: |
        python scripts/main.py
